export enum ResourceCategory {
  SLEEPING_POD = 'SLEEPING_POD',
  FOOD_STATION = 'FOOD_STATION',
  OXYGEN_UNIT = 'OXYGEN_UNIT',
  MEDICAL_BAY = 'MEDICAL_BAY',
  HYGIENE_POD = 'HYGIENE_POD',
  FITNESS_CENTER = 'FITNESS_CENTER',
  PRIVATE_CABIN = 'PRIVATE_CABIN',
  REC_DECK = 'REC_DECK',
}
